
info:
  description: API of the server for Fief Diplomatie
  title: Fief Diplomatie API
  version: 1.0.0
basePath: /v1
consumes: ["application/json"]
produces: ["application/json"]
schemes: ["http"]
swagger: "2.0"
securityDefinitions:
  Bearer:
    type: apiKey
    in: header
    name: Authorization
paths:
  /register:
    post:
      description: Register a new user
      tags: [user]
      operationId: Register
      parameters:
        - name: signup
          in: body
          description: Registration payload
          required: true
          schema:
            $ref: '#/definitions/RegisterUser'
      responses:
        200:
          description: Successful registration
          schema:
            $ref: '#/definitions/SuccessResponse'
        400:
          description: Bad Request
        500:
          schema:
            type: string
          description: Server error
  /signin:
    post:
      tags: [user]
      operationId: Login
      consumes:
        - "application/json"
      description: Signin with login/password and retrieve JWT token for further requests
      parameters:
        - name: Login
          in: body
          required: true
          schema:
            $ref: '#/definitions/LoginInfo'
      responses:
        200:
          description: Successful login
          schema:
            $ref: '#/definitions/LoginSuccess'
        400:
          description: Bad Request
        404:
          schema:
            type: string
          description: User not found
        500:
          schema:
            type: string
          description: Server error
  /games:
    get:
      tags: [game]
      security:
        - Bearer: []
      description: List existing games
      responses:
        '200':
          description: TODO
  /games/new:
    post:
      tags: [manage]
      security:
        - Bearer: []
      description: Create a new game
      responses:
        '200':
          description: TODO
  /games/{id}/join:
    post:
      tags: [manage]
      security:
        - Bearer: []
      description: Join an existing game
      parameters:
      - name: id
        in: path
        required: true
        type: string
      responses:
        '200':
          description: TODO
  /games/{id}/status:
    get:
      tags: [game]
      security:
        - Bearer: []
      description: Get current state of an existing game
      parameters:
      - name: id
        in: path
        required: true
        type: string
      responses:
        '200':
          description: TODO
  /games/{id}/instructions:
    post:
      tags: [game]
      security:
        - Bearer: []
      description: Post an instruction for the authenticated user on the session, if no instruction defined
      parameters:
      - name: id
        in: path
        required: true
        type: string
      - name: instruction
        in: body
        schema: 
          type: string
      responses:
        '200':
          description: TODO
    get:
      tags: [game]
      security:
        - Bearer: []
      description: Retrieve the current instructions for the authenticated user
      parameters:
      - name: id
        in: path
        required: true
        type: string
      responses:
        '200':
          description: TODO


definitions:
  SuccessResponse:
    type: object
    properties:
      success:
        type: boolean
      message:
        type: string
  RegisterUser:
    type: object
    required:
      - email
      - login
      - password
    properties:
      email:
        type: string
      login:
        type: string
      password:
        type: string
  LoginInfo:
    type: object
    required:
      - login
      - password
    properties:
      login:
        type: string
      password:
        type: string
  LoginSuccess:
    type: object
    properties:
      success:
        type: boolean
      token:
        type: string