// Code generated by go-swagger; DO NOT EDIT.

package game

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetGamesIDHandlerFunc turns a function with the right signature into a get games ID handler
type GetGamesIDHandlerFunc func(GetGamesIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetGamesIDHandlerFunc) Handle(params GetGamesIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetGamesIDHandler interface for that can handle valid get games ID params
type GetGamesIDHandler interface {
	Handle(GetGamesIDParams, interface{}) middleware.Responder
}

// NewGetGamesID creates a new http.Handler for the get games ID operation
func NewGetGamesID(ctx *middleware.Context, handler GetGamesIDHandler) *GetGamesID {
	return &GetGamesID{Context: ctx, Handler: handler}
}

/* GetGamesID swagger:route GET /games/{id} game getGamesId

Get current state of an existing game

*/
type GetGamesID struct {
	Context *middleware.Context
	Handler GetGamesIDHandler
}

func (o *GetGamesID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetGamesIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
