// Code generated by go-swagger; DO NOT EDIT.

package game

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetGamesIDStatusOKCode is the HTTP code returned for type GetGamesIDStatusOK
const GetGamesIDStatusOKCode int = 200

/*GetGamesIDStatusOK TODO

swagger:response getGamesIdStatusOK
*/
type GetGamesIDStatusOK struct {
}

// NewGetGamesIDStatusOK creates GetGamesIDStatusOK with default headers values
func NewGetGamesIDStatusOK() *GetGamesIDStatusOK {

	return &GetGamesIDStatusOK{}
}

// WriteResponse to the client
func (o *GetGamesIDStatusOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
