// Code generated by go-swagger; DO NOT EDIT.

package game

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetGamesIDOKCode is the HTTP code returned for type GetGamesIDOK
const GetGamesIDOKCode int = 200

/*GetGamesIDOK TODO

swagger:response getGamesIdOK
*/
type GetGamesIDOK struct {
}

// NewGetGamesIDOK creates GetGamesIDOK with default headers values
func NewGetGamesIDOK() *GetGamesIDOK {

	return &GetGamesIDOK{}
}

// WriteResponse to the client
func (o *GetGamesIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
