// Code generated by go-swagger; DO NOT EDIT.

package game

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetGamesOKCode is the HTTP code returned for type GetGamesOK
const GetGamesOKCode int = 200

/*GetGamesOK TODO

swagger:response getGamesOK
*/
type GetGamesOK struct {
}

// NewGetGamesOK creates GetGamesOK with default headers values
func NewGetGamesOK() *GetGamesOK {

	return &GetGamesOK{}
}

// WriteResponse to the client
func (o *GetGamesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
