// Code generated by go-swagger; DO NOT EDIT.

package game

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetGamesIDStatusHandlerFunc turns a function with the right signature into a get games ID status handler
type GetGamesIDStatusHandlerFunc func(GetGamesIDStatusParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetGamesIDStatusHandlerFunc) Handle(params GetGamesIDStatusParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetGamesIDStatusHandler interface for that can handle valid get games ID status params
type GetGamesIDStatusHandler interface {
	Handle(GetGamesIDStatusParams, interface{}) middleware.Responder
}

// NewGetGamesIDStatus creates a new http.Handler for the get games ID status operation
func NewGetGamesIDStatus(ctx *middleware.Context, handler GetGamesIDStatusHandler) *GetGamesIDStatus {
	return &GetGamesIDStatus{Context: ctx, Handler: handler}
}

/* GetGamesIDStatus swagger:route GET /games/{id}/status game getGamesIdStatus

Get current state of an existing game

*/
type GetGamesIDStatus struct {
	Context *middleware.Context
	Handler GetGamesIDStatusHandler
}

func (o *GetGamesIDStatus) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetGamesIDStatusParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
