// Code generated by go-swagger; DO NOT EDIT.

package game

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetGamesIDInstructionsOKCode is the HTTP code returned for type GetGamesIDInstructionsOK
const GetGamesIDInstructionsOKCode int = 200

/*GetGamesIDInstructionsOK TODO

swagger:response getGamesIdInstructionsOK
*/
type GetGamesIDInstructionsOK struct {
}

// NewGetGamesIDInstructionsOK creates GetGamesIDInstructionsOK with default headers values
func NewGetGamesIDInstructionsOK() *GetGamesIDInstructionsOK {

	return &GetGamesIDInstructionsOK{}
}

// WriteResponse to the client
func (o *GetGamesIDInstructionsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
