// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"

	"fief/models"
)

// NewPostSignupCodeParams creates a new PostSignupCodeParams object
//
// There are no default values defined in the spec.
func NewPostSignupCodeParams() PostSignupCodeParams {

	return PostSignupCodeParams{}
}

// PostSignupCodeParams contains all the bound params for the post signup code operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostSignupCode
type PostSignupCodeParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Authorization code that allow player to signup in server
	  Required: true
	  In: path
	*/
	Code string
	/*
	  Required: true
	  In: body
	*/
	Credentials *models.Credentials
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostSignupCodeParams() beforehand.
func (o *PostSignupCodeParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rCode, rhkCode, _ := route.Params.GetOK("code")
	if err := o.bindCode(rCode, rhkCode, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Credentials
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("credentials", "body", ""))
			} else {
				res = append(res, errors.NewParseError("credentials", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(context.Background())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Credentials = &body
			}
		}
	} else {
		res = append(res, errors.Required("credentials", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindCode binds and validates parameter Code from path.
func (o *PostSignupCodeParams) bindCode(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Code = raw

	return nil
}
