// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostSignupCodeHandlerFunc turns a function with the right signature into a post signup code handler
type PostSignupCodeHandlerFunc func(PostSignupCodeParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostSignupCodeHandlerFunc) Handle(params PostSignupCodeParams) middleware.Responder {
	return fn(params)
}

// PostSignupCodeHandler interface for that can handle valid post signup code params
type PostSignupCodeHandler interface {
	Handle(PostSignupCodeParams) middleware.Responder
}

// NewPostSignupCode creates a new http.Handler for the post signup code operation
func NewPostSignupCode(ctx *middleware.Context, handler PostSignupCodeHandler) *PostSignupCode {
	return &PostSignupCode{Context: ctx, Handler: handler}
}

/* PostSignupCode swagger:route POST /signup/{code} postSignupCode

Create user with login/password

*/
type PostSignupCode struct {
	Context *middleware.Context
	Handler PostSignupCodeHandler
}

func (o *PostSignupCode) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostSignupCodeParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
