POST http://127.0.0.1:3000/api/v1/auth/signup
content-type: application/json

{
  "email": "test@test.com",
  "login": "Eole",
  "password": "mgzkleghmksdjbgnmkdsjbgnqzebjnzeqbjgqzejgzeqjk"
}
###
# @name login
POST http://127.0.0.1:8080/api/v1/auth/signin
content-type: application/json

{
  "login": "Eole",
  "password": "mgzkleghmksdjbgnmkdsjbgnqzebjnzeqbjgqzejgzeqjk"
}

###
@token= {{login.response.body.token}}

###
GET http://127.0.0.1:8080/api/v1/games
Accept: application/json
content-type: application/json
Authorization: Bearer {{token}}
