POST http://127.0.0.1:8080/v1/register
content-type: application/json

{
  "email": "test@test.com",
  "login": "Eole",
  "password": "mgzkleghmksdjbgnmkdsjbgnqzebjnzeqbjgqzejgzeqjk"
}
###

POST http://127.0.0.1:8080/v1/signin
content-type: application/json

{
  "login": "Eole",
  "password": "mgzkleghmksdjbgnmkdsjbgnqzebjnzeqbjgqzejgzeqjk"
}