// Code generated by go-swagger; DO NOT EDIT.

package manage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostGamesIDJoinOKCode is the HTTP code returned for type PostGamesIDJoinOK
const PostGamesIDJoinOKCode int = 200

/*PostGamesIDJoinOK TODO

swagger:response postGamesIdJoinOK
*/
type PostGamesIDJoinOK struct {
}

// NewPostGamesIDJoinOK creates PostGamesIDJoinOK with default headers values
func NewPostGamesIDJoinOK() *PostGamesIDJoinOK {

	return &PostGamesIDJoinOK{}
}

// WriteResponse to the client
func (o *PostGamesIDJoinOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
