// Code generated by go-swagger; DO NOT EDIT.

package manage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostGamesNewHandlerFunc turns a function with the right signature into a post games new handler
type PostGamesNewHandlerFunc func(PostGamesNewParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostGamesNewHandlerFunc) Handle(params PostGamesNewParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostGamesNewHandler interface for that can handle valid post games new params
type PostGamesNewHandler interface {
	Handle(PostGamesNewParams, interface{}) middleware.Responder
}

// NewPostGamesNew creates a new http.Handler for the post games new operation
func NewPostGamesNew(ctx *middleware.Context, handler PostGamesNewHandler) *PostGamesNew {
	return &PostGamesNew{Context: ctx, Handler: handler}
}

/* PostGamesNew swagger:route POST /games/new manage postGamesNew

Create a new game

*/
type PostGamesNew struct {
	Context *middleware.Context
	Handler PostGamesNewHandler
}

func (o *PostGamesNew) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostGamesNewParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
