// Code generated by go-swagger; DO NOT EDIT.

package manage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostGamesNewOKCode is the HTTP code returned for type PostGamesNewOK
const PostGamesNewOKCode int = 200

/*PostGamesNewOK TODO

swagger:response postGamesNewOK
*/
type PostGamesNewOK struct {
}

// NewPostGamesNewOK creates PostGamesNewOK with default headers values
func NewPostGamesNewOK() *PostGamesNewOK {

	return &PostGamesNewOK{}
}

// WriteResponse to the client
func (o *PostGamesNewOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
